window.COOPACS = {
  sanisidro:{nombre:"COOPAC San Isidro",subdominio:"sanisidro",participa:false,logo:""},
  crediplata:{nombre:"COOPAC Crediplata",subdominio:"crediplata",participa:false,logo:""},
  mfprisma:{nombre:"COOPAC MF Prisma",subdominio:"mfprisma",participa:false,logo:""},
  etica:{nombre:"COOPAC Ética",subdominio:"etica",participa:false,logo:""},
  tocache:{nombre:"COOPAC Tocache",subdominio:"tocache",participa:false,logo:""},
  inclusiva:{nombre:"COOPAC Inclusiva",subdominio:"inclusiva",participa:false,logo:""},
  sancristobal:{nombre:"COOPAC San Cristóbal",subdominio:"sancristobal",participa:true,logo:"sancristobal.png"},
  norandino:{nombre:"COOPAC Norandino",subdominio:"norandino",participa:true,logo:""},
  servicredit:{nombre:"COOPAC Servicredit",subdominio:"servicredit",participa:true,logo:""},
  sanfranciscodemocupe:{nombre:"COOPAC San Francisco de Mocupe",subdominio:"sanfranciscodemocupe",participa:true,logo:""},
  continental:{nombre:"COOPAC Continental",subdominio:"continental",participa:true,logo:""},
  pacifico:{nombre:"COOPAC Pacífico",subdominio:"pacifico",participa:true,logo:""},
  sanfranciscojavier:{nombre:"COOPAC San Francisco Javier",subdominio:"sanfranciscojavier",participa:true,logo:""},
  laportuaria:{nombre:"COOPAC La Portuaria",subdominio:"laportuaria",participa:true,logo:""},
  santodomingodeguzman:{nombre:"COOPAC Santo Domingo de Guzmán",subdominio:"santodomingodeguzman",participa:true,logo:""},
  chiquinquira:{nombre:"COOPAC Chiquinquirá",subdominio:"chiquinquira",participa:true,logo:""},
  sanhilarion:{nombre:"COOPAC San Hilarión",subdominio:"sanhilarion",participa:true,logo:""},
  abaco:{nombre:"COOPAC Ábaco",subdominio:"abaco",participa:true,logo:""},
  fondesurco:{nombre:"COOPAC Fondesurco",subdominio:"fondesurco",participa:true,logo:""},
  amazonas:{nombre:"COOPAC Amazonas",subdominio:"amazonas",participa:true,logo:""},
  centrocoop:{nombre:"COOPAC Centrocoop",subdominio:"centrocoop",participa:true,logo:""},
  finansol:{nombre:"COOPAC Finansol",subdominio:"finansol",participa:true,logo:""},
  cacil:{nombre:"COOPAC Ilo - CACIL",subdominio:"cacil",participa:true,logo:""},
  larehabilitadora:{nombre:"COOPAC La Rehabilitadora",subdominio:"larehabilitadora",participa:true,logo:""},
  sanfrancisco:{nombre:"COOPAC San Francisco",subdominio:"sanfrancisco",participa:true,logo:""},
  toquepala:{nombre:"COOPAC Toquepala",subdominio:"toquepala",participa:true,logo:""}
};
