window.COOPACS = {
  sanisidro:{nombre:"COOPAC San Isidro",subdominio:"sanisidro",participa:true,logo:"assets/coopac/sanisidro.png"},
  crediplata:{nombre:"COOPAC Crediplata",subdominio:"crediplata",participa:false,logo:"assets/coopac/crediplata.png"},
  mfprisma:{nombre:"COOPAC MF Prisma",subdominio:"mfprisma",participa:false,logo:"assets/coopac/mfprisma.png"},
  etica:{nombre:"COOPAC Ética",subdominio:"etica",participa:false,logo:"assets/coopac/etica.png"},
  tocache:{nombre:"COOPAC Tocache",subdominio:"tocache",participa:false,logo:"assets/coopac/tocache.png"},
  inclusiva:{nombre:"COOPAC Inclusiva",subdominio:"inclusiva",participa:true,logo:"assets/coopac/inclusiva.png"},
  sancristobal:{nombre:"COOPAC San Cristóbal",subdominio:"sancristobal",participa:true,logo:"assets/coopac/sancristobal.png"},
  norandino:{nombre:"COOPAC Norandino",subdominio:"norandino",participa:true,logo:"assets/coopac/norandino.png"},
  servicredit:{nombre:"COOPAC Servicredit",subdominio:"servicredit",participa:false,logo:"assets/coopac/servicredit.png"},
  sanfranciscodemocupe:{nombre:"COOPAC San Francisco de Mocupe",subdominio:"sanfranciscodemocupe",participa:false,logo:"assets/coopac/sanfranciscodemocupe.png"},
  continental:{nombre:"COOPAC Continental",subdominio:"continental",participa:false,logo:"assets/coopac/continental.png"},
  pacifico:{nombre:"COOPAC Pacífico",subdominio:"pacifico",participa:false,logo:"assets/coopac/pacifico.png"},
  sanfranciscojavier:{nombre:"COOPAC San Francisco Javier",subdominio:"sanfranciscojavier",participa:true,logo:"assets/coopac/sanfranciscojavier.png"},
  laportuaria:{nombre:"COOPAC La Portuaria",subdominio:"laportuaria",participa:false,logo:"assets/coopac/laportuaria.png"},
  santodomingodeguzman:{nombre:"COOPAC Santo Domingo de Guzmán",subdominio:"santodomingodeguzman",participa:false,logo:"assets/coopac/santodomingodeguzman.png"},
  chiquinquira:{nombre:"COOPAC Chiquinquirá",subdominio:"chiquinquira",participa:false,logo:"assets/coopac/chiquinquira.png"},
  sanhilarion:{nombre:"COOPAC San Hilarión",subdominio:"sanhilarion",participa:true,logo:"assets/coopac/sanhilarion.png"},
  abaco:{nombre:"COOPAC Ábaco",subdominio:"abaco",participa:false,logo:"assets/coopac/abaco.png"},
  fondesurco:{nombre:"COOPAC Fondesurco",subdominio:"fondesurco",participa:false,logo:"assets/coopac/fondesurco.png"},
  amazonas:{nombre:"COOPAC Amazonas",subdominio:"amazonas",participa:false,logo:"assets/coopac/amazonas.png"},
  centrocoop:{nombre:"COOPAC Centrocoop",subdominio:"centrocoop",participa:false,logo:"assets/coopac/centrocoop.png"},
  finansol:{nombre:"COOPAC Finansol",subdominio:"finansol",participa:false,logo:"assets/coopac/finansol.png"},
  cacil:{nombre:"COOPAC Ilo - CACIL",subdominio:"cacil",participa:false,logo:"assets/coopac/cacil.png"},
  larehabilitadora:{nombre:"COOPAC La Rehabilitadora",subdominio:"larehabilitadora",participa:false,logo:"assets/coopac/larehabilitadora.png"},
  sanfrancisco:{nombre:"COOPAC San Francisco",subdominio:"sanfrancisco",participa:false,logo:"assets/coopac/sanfrancisco.png"},
  toquepala:{nombre:"COOPAC Toquepala",subdominio:"toquepala",participa:false,logo:"assets/coopac/toquepala.png"}
};
